# Generated by Django 6.0 on 2025-12-14 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, unique=True, verbose_name="Số bàn"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sức chứa",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("indoor", "Trong nhà"),
                            ("outdoor", "Ngoài trời"),
                            ("vip", "Phòng VIP"),
                        ],
                        default="indoor",
                        max_length=50,
                        verbose_name="Vị trí",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Có sẵn"),
                            ("occupied", "Đang sử dụng"),
                            ("reserved", "Đã đặt"),
                            ("maintenance", "Bảo trì"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
            ],
            options={
                "verbose_name": "Bàn",
                "verbose_name_plural": "Bàn",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=100, verbose_name="Tên khách"),
                ),
                (
                    "guest_phone",
                    models.CharField(max_length=15, verbose_name="SĐT khách"),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("date", models.DateField(verbose_name="Ngày đặt")),
                ("time", models.TimeField(verbose_name="Giờ đặt")),
                (
                    "number_of_guests",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Số khách",
                    ),
                ),
                (
                    "duration_hours",
                    models.IntegerField(default=2, verbose_name="Thời gian (giờ)"),
                ),
                (
                    "special_request",
                    models.TextField(blank=True, verbose_name="Yêu cầu đặc biệt"),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("birthday", "Sinh nhật"),
                            ("anniversary", "Kỷ niệm"),
                            ("business", "Công việc"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                        verbose_name="Dịp",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("checked_in", "Đã check-in"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                            ("no_show", "Không đến"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "deposit_required",
                    models.BooleanField(default=False, verbose_name="Yêu cầu đặt cọc"),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Số tiền cọc",
                    ),
                ),
                (
                    "deposit_paid",
                    models.BooleanField(default=False, verbose_name="Đã đặt cọc"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="reservations.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đặt bàn",
                "verbose_name_plural": "Đặt bàn",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
