# Generated by Django 6.0 on 2025-12-13 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên danh mục")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Thứ tự")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên")),
                ("slug", models.SlugField(unique=True)),
                ("position", models.CharField(max_length=100, verbose_name="Chức vụ")),
                ("bio", models.TextField(verbose_name="Tiểu sử")),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Chuyên môn"
                    ),
                ),
                ("image", models.ImageField(upload_to="chefs/", verbose_name="Ảnh")),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang làm việc"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Đầu bếp",
                "verbose_name_plural": "Đầu bếp",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên món")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Mô tả")),
                ("recipe", models.TextField(blank=True, verbose_name="Công thức")),
                (
                    "ingredients",
                    models.TextField(blank=True, verbose_name="Nguyên liệu"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Giá khuyến mãi",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu/", verbose_name="Ảnh")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Còn hàng"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Nổi bật"),
                ),
                (
                    "is_vegetarian",
                    models.BooleanField(default=False, verbose_name="Chay"),
                ),
                ("is_spicy", models.BooleanField(default=False, verbose_name="Cay")),
                (
                    "preparation_time",
                    models.IntegerField(
                        default=15, verbose_name="Thời gian chuẩn bị (phút)"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Lượt xem"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="restaurant.category",
                        verbose_name="Danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Món ăn",
                "verbose_name_plural": "Món ăn",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="restaurant.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
                "ordering": ["-created_at"],
                "unique_together": {("menu_item", "user")},
            },
        ),
    ]
