# Generated by Django 6.0 on 2025-12-14 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Phần trăm"),
                            ("fixed", "Số tiền cố định"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá trị giảm"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Đơn hàng tối thiểu",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Giảm tối đa",
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Giới hạn sử dụng"
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="Đã sử dụng"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Có hiệu lực từ")),
                ("valid_to", models.DateTimeField(verbose_name="Có hiệu lực đến")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
            ],
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Mã giảm giá",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Giao hàng"),
                            ("pickup", "Lấy tại quán"),
                            ("dine_in", "Ăn tại quán"),
                        ],
                        default="delivery",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("preparing", "Đang chuẩn bị"),
                            ("ready", "Sẵn sàng"),
                            ("delivering", "Đang giao"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_name",
                    models.CharField(max_length=100, verbose_name="Tên người nhận"),
                ),
                (
                    "delivery_phone",
                    models.CharField(max_length=15, verbose_name="SĐT người nhận"),
                ),
                (
                    "delivery_address",
                    models.TextField(verbose_name="Địa chỉ giao hàng"),
                ),
                ("delivery_note", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tạm tính",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Phí vận chuyển",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Giảm giá",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Thanh toán khi nhận hàng"),
                            ("bank_transfer", "Chuyển khoản ngân hàng"),
                            ("momo", "Ví MoMo"),
                            ("zalopay", "ZaloPay"),
                        ],
                        default="cod",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ thanh toán"),
                            ("paid", "Đã thanh toán"),
                            ("refunded", "Đã hoàn tiền"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Đơn giá"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú món")),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn hàng",
                "verbose_name_plural": "Chi tiết đơn hàng",
            },
        ),
    ]
